services:
  - type: web
    name: chatporter
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
    autoDeploy: true
